### ISSUE TITLE
Remove hard link

### ISSUE THREAD

**Issue by dlesnoff** [Smarcy/connect_the_dotfiles#1]
In the first function, I can see the following hard link :
```nim
    if (readFile(StorageFile).contains(chosenDotfile)) or symlinkExists(chosenDotfile):
      copyFileToDir("/home/marc/git/dotfiles/.vimrc", DotfilesLocation)
```
Could you change this to `~/git/dotfiles/.vimrc` ? I think you might better replace this with a variable that you define at the top of your source file.

**Comment by Smarcy** [comment]
Oh, how did I not see this for so long?! Good catch, thank you. Should be fixed by now!
