### ISSUE TITLE
Which Linux Distribution is supported ?

### ISSUE THREAD

**Issue by dlesnoff** [Smarcy/connect_the_dotfiles#2]
Right now, the following is announced :
```nim
Right now I am concentrating on Linux only and I do not intend to port to Windows anytime, yet.
```
I do not even see why we would organize dotfiles in Windows. The configuration is more register based and the OS does not really permit the configuration.

We do not know which distribution of Linux you use, or on which distribution you have tested your program.

**Comment by Smarcy** [comment]
You are right about symlinks on Windows of course, didn't really thought this statement through.
Anyway, I adjusted that part of the README and added my use Linux distribution. Thank you for your input!
